### ISSUE TITLE
Rules cannot be renamed

### ISSUE THREAD

**Issue by ygoe** [nextcloud/files_accesscontrol#100]
When entering a new text into the textbox of an existing ruleset, nothing happens. After reloading the page, the old name is there again. Clicking the unsuspicious trash bin icon next to the name field immediately deletes the entire ruleset, not even asking me. If I don't like the name of a ruleset, I'll have to create a new one with all the same rules and a better name. Is that intentional?

**Comment by nickvergessen** [comment]
> ![bildschirmfoto von 2018-05-04 15-33-34](https://user-images.githubusercontent.com/213943/39630796-ba134d32-4fb0-11e8-859d-eb020bcd7e3b.png)

After clicking outside of the input field, The rule is marked with the orange "edited" marker on the left side and the "Save" button appears. After saving and reloading the name is whatever I changed it to.
