### ISSUE TITLE
Admin page not loading

### ISSUE THREAD

**Issue by orodruim** [nextcloud/files_accesscontrol#104]
I use nextcloud 12 on a ubuntu 14.04 server. I have installed app "File Access Control" and it worked fine. I started to create rules, saving them OK. But once an error was shown (I could not capture the info on the screen) and now the admin page keeps "Loading" (image: https://i.stack.imgur.com/atDnT.jpg)

I have uninstalled and reinstalled the app, but always the same. Any idea?

This is what I get in log file:
`

> Error | index | TypeError: Argument  1 passed to OCA\WorkflowEngine\Manager::getChecks() must be of the type  array, object given, called in  /var/www/spec/apps/workflowengine/lib/Controller/FlowOperations.php on  line 115 | 2018-07-18T17:14:24+0200
> -- | -- | -- | --
> Error | index | TypeError: Argument  1 passed to OCA\WorkflowEngine\Manager::getChecks() must be of the type  array, object given, called in  /var/www/spec/apps/workflowengine/lib/Controller/FlowOperations.php on  line 115

`

Thanks in advance.

### Steps to reproduce
1. Open administration page
2. Click on file access control

### Expected behaviour
It should show the created rules

### Actual behaviour
It keeps loading

### Server configuration
Ubuntu 14.04 - Nextcloud 12

**Operating system**:
Ubuntu 14.04
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12
**Where did you install Nextcloud from:**

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

```

**Nextcloud configuration:**

```
  "system": {
        "instanceid": "ocys6p0noi9o",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "portalcal1.campinaverde.com",
            "h2722805.stratoserver.net"
        ],
        "datadirectory": "\/var\/www\/spec\/data",
        "overwrite.cli.url": "http:\/\/h2722805.stratoserver.net",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filesystem_check_changes": 1,
        "maintenance": false,
        "theme": "",
        "logtimezone": "Europe\/Berlin",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "log_rotate_size": "104857600",
        "loglevel": 2,
        "filelocking.enabled": false,
        "trashbin_retention_obligation": "auto, 15"
    }

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by orodruim** [comment]
Thanks for your answer.
How should I do this?
This is the content from this tables:
`
MariaDB [nextcloud]> select * from oc_flow_checks;
+----+----------------------------------------------+----------+--------------------+----------------------------------+
| id | class                                        | operator | value              | hash                             |
+----+----------------------------------------------+----------+--------------------+----------------------------------+
|  1 | OCA\WorkflowEngine\Check\FileMimeType        | !is      | application/zip    | 025a171b648a41c0c267eac2cdd88942 |
|  2 | OCA\WorkflowEngine\Check\FileMimeType        | is       | application/pdf    | 4de1966635f169e3fc2c0430363aed2b |
|  3 | OCA\WorkflowEngine\Check\FileMimeType        | !is      | application/pdf    | cbc80bafad13a1806089c3d0fa5e4722 |
|  4 | OCA\WorkflowEngine\Check\UserGroupMembership | is       | studio             | 5b7d6d9ebb7b611effd73c8c770f75f6 |
|  5 | OCA\WorkflowEngine\Check\FileMimeType        | !is      | application/msword | 54dc726803314d2295719cdee9d63e4b |
+----+----------------------------------------------+----------+--------------------+----------------------------------+
5 rows in set (0.00 sec)

MariaDB [nextcloud]> select * from oc_flow_operations;
+----+----------------------------------+----------------+---------------------+-----------+
| id | class                            | name           | checks              | operation |
+----+----------------------------------+----------------+---------------------+-----------+
|  1 | OCA\FilesAccessControl\Operation | Studio sharing | {"0":1,"1":4,"3":5} | deny      |
+----+----------------------------------+----------------+---------------------+-----------+
1 row in set (0.00 sec)
`

**Comment by nickvergessen** [comment]
Can you try to modify the [`apps/workflowengine/lib/Controller/FlowOperations.php` file](https://github.com/nextcloud/server/blob/410e0fc28f25835c4b10e31066b641387cb53391/apps/workflowengine/lib/Controller/FlowOperations.php#L114).
In line 114 find:
```php
$checkIds = json_decode($operation['checks']);
```
replace with:
```php
$checkIds = json_decode($operation['checks'], true);
```

**Comment by orodruim** [comment]
Wow!!! You are so helpful and fast!

It works fine. Now I can go to admin page again.

Thanks a lot!

**Comment by nickvergessen** [comment]
Let's keep this open until we fixed it in the product itself

**Comment by orodruim** [comment]
Ok, great.
