### ISSUE TITLE
在nextcloud服务器上无法下载文件

### ISSUE THREAD

**Issue by 15105753330** [nextcloud/files_accesscontrol#106]
### Steps to reproduce
1.可以在nextcloud服务器上创建，上传文件。
2.上传完的文件无法下载。
3.在本地创建的文件夹可以下载，无法下载的文件拉到该文件夹下还是无法下载。

### Expected behaviour

应该是可以把上传的文件下载下来的
### Actual behaviour

点击下载文件，连续下载中断3次然后下载失败。
### Server configuration

**Operating system**:Centos7

**Web server:**阿里云

**Database:**mysql

**PHP version:**PHP 7.0.30

**Nextcloud version:**nextcloud13

**Where did you install Nextcloud from:**Centos7

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Can you please report your issue in english language?

**Comment by 15105753330** [comment]
yes，I will.


| |
15105753330
|
|
邮箱：15105753330@163.com
|

Signature is customized by Netease Mail Master

在2018年08月21日 22:39，Joas Schilling 写道：

Can you please report your issue in english language?
