### ISSUE TITLE
Configurating FileAccessControl

### ISSUE THREAD

**Issue by tschroeer** [nextcloud/files_accesscontrol#116]
Hello

I want to restrict access to files and / or folders for specific user groups. For this I have the FileAccessControl app installed.

I have created the following folder structure:

Location A
| — 10000 project name
| — Offers
| — Delivery notes
| — bills
| — 10001 project name
| — Offers
| — Delivery notes
| — bills
Location B
| — 10002 Project name
| — Offers
| — Delivery notes
| — bills
| — 10003 project name
| — Offers
| — Delivery notes
| — bills

All folders and files belong to a special projects user. The location folders have been shared for the respective groups. I have created two groups (FIBU and DISPO) and assigned my users to these groups. In addition, I have tagged the locations with a location tag. I have tagged the individual project folders with the location tag, a FIBU tag, and a DISPO tag.

Now I have created the following rule groups in the FileAccessControl app:

ACL_DISPO
File collaborative tag is tagged with DISPO_TAG
User group membership is not a member of DISPO

ACL_FIBU
File collaborative tag is tagged with FIBU_TAG
User group membership is not a member of the FIBU

If these two rule groups are active, I can not access the project folder. However, if I delete one of both rule groups, then I have full access to all subfolders and all files.

Why is that so? I understood the manual to mean that if all the rules of a rule group are true then access is denied. That is not the case.

Can someone explain to me how I must set appropriate rules or TAGs?

**Comment by nickvergessen** [comment]
That is actually exactly how it should work.
Do you mind to repost the folder structure and add the assigned tags in brackets behind them?

**Comment by tschroeer** [comment]
Location A [Location_A_TAG] (shared with FIBU Group and DISPO Group)
| — 10000 project name [Location_A_TAG]
       | — Offers
       | — Delivery notes [DISPO_TAG]
       | — bills [FIBU_TAG]
| — 10001 project name [Location_A_TAG]
       | — Offers
       | — Delivery notes [DISPO_TAG]
       | — bills [FIBU_TAG]
Location B [Location_B_TAG]  (shared with FIBU Group and DISPO Group)
| — 10002 Project name [Location_B_TAG]
       | — Offers
       | — Delivery notes [DISPO_TAG]
       | — bills [FIBU_TAG]
| — 10003 project name [Location_B_TAG]
       | — Offers
       | — Delivery notes [DISPO_TAG]
       | — bills [FIBU_TAG]

**Comment by nickvergessen** [comment]
Works fine here, so this isn't a bug report, it seems to be a support request. Please use https://
portal.nextcloud.com for those or look on the home user forums on https://help.nextcloud.com
