### ISSUE TITLE
Can't acces File Access Control Configuration

### ISSUE THREAD

**Issue by Perry2493** [nextcloud/files_accesscontrol#117]
Hi, 
i have a lil Problem - but don't know since when exactly it exists.
Last time we updated Nextcloud was on Oct. 19th to 12.0.12 - maybe the Problem exists since that update... 

At the moment i am not able to open the Configuration of the File Access Control - instead it is just loading like forever:
![grafik](https://user-images.githubusercontent.com/37185307/48341179-b4dc6800-e66c-11e8-8ec3-1ee22746e4e0.png)

How can i fix this behavior - found it, cause it seems like some of our rules are locking out some people which shouldn't be affected at all...

Thank you!

### Steps to reproduce
1. open File Access Control Configuration

### Expected behaviour
Show active Ruleset

### Actual behaviour
Endless loading

### Server configuration
**Operating system**:
Ubuut 16.04.4 LTS

**Web server:**
apache2 2.4.18

**Database:**
mariadb10 10.0.36

**PHP version:**
php7 7.0.32

**Nextcloud version:** (see Nextcloud admin page)
12.0.12

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.1.0
  - comments: 1.2.0
  - dav: 1.3.1
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.6
  - onlyoffice: 2.0.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - announcementcenter
  - files_external
  - groupfolders
  - user_external

**Nextcloud configuration:**
{
"system": {
"instanceid": "ocmh2lhz0ngx",
"passwordsalt": "REMOVED SENSITIVE VALUE",
"secret": "REMOVED SENSITIVE VALUE",
"trusted_domains": [
"NC-FQDN",
"NC-Server.domain.xx",
"IP",
],
"trusted_proxies": [
"Proxy-IP"
],
"forwarded_for_headers": [
"HTTP_X_FORWARDED_FOR",
"HTTP_FORWARDED_FOR"
],
"datadirectory": "/mnt/nextcloud_data",
"overwrite.cli.url": "https://server.domain.xx",
"enable_previews": false,
"dbtype": "mysql",
"version": "12.0.12.2",
"dbname": "nextcloud",
"dbhost": "localhost",
"dbport": "",
"dbtableprefix": "oc_",
"dbuser": "REMOVED SENSITIVE VALUE",
"dbpassword": "REMOVED SENSITIVE VALUE",
"logtimezone": "UTC",
"installed": true,
"memcache.local": "\OC\Memcache\APCu",
"activity_expire_days": 180,
"preview_max_x": "960",
"preview_max_y": "720",
"ldapIgnoreNamingRules": false,
"ldapProviderFactory": "\OCA\User_LDAP\LDAPProviderFactory",
"loglevel": 2,
"logfile": "/var/log/nextcloud.log",
"maintenance": false,
"singleuser": true,
"updater.release.channel": "production",
"mail_from_address": "nextcloud",
"mail_smtpmode": "smtp",
"mail_smtpauthtype": "PLAIN",
"mail_domain": "domain.xx",
"mail_smtphost": "SMTP-IP",
"mail_smtpport": "25",
"theme": "",
"skeletondirectory": "",
"filesystem_check_changes": 0
}
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS-Share from an NetApp

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes - ActiveDirectory

### Client configuration
**Browser:**
testet on multiple devices running Chrome, Firefox, Edge

**Operating system:**
Windows10

### Logs

no logs on created while trying to access File Access Control Configuration

**Comment by nickvergessen** [comment]
When you use firefox, press F12, switch to the console tab of he new window and then go into the browser and navigate to the section again, it should show you an error.

**Comment by Perry2493** [comment]
Thank you for that fast reply! 
getting the following errors here: 

```
JQMIGRATE: Migrate is installed, version 1.4.0                  core.js:7:542
SyntaxError: unexpected token: identifier                       systemtagmodel.js:1:10
TypeError: this.model is undefined                              core.js:3682:7
Source-Map-Fehler: request failed with status 503
Ressourcen-Adresse: https://*my_domain*/core/vendor/core.js?v=6b811460-15
Source-Map-Adresse: purify.min.js.map
```

To be honest, i've no clue what that means for me..
Thanks for your help!

**Comment by Perry2493** [comment]
Seems like we found the Problem.
Somehow that mentioned "core.js"-File was replaced by a File which looked pretty much like an README-File...
We replaced it with an core.js file from a fresh download an now we can access die FileAccesControl-Configuration again.

Don't know how that could happen - but thanks for your help!
