### ISSUE TITLE
Activity in restricted folders visible to all users

### ISSUE THREAD

**Issue by floriandusch** [nextcloud/files_accesscontrol#125]
### Steps to reproduce
1. Folder 1 is shared with All users
2. Folder 2 inside of Folder 1 is protected through Tags limiting access to only one group of users
3. Users that are not part of that group can't access Folder 2, so that works as expected
4. But: Any activity inside the restricted Folder 2 shows up in the activity stream of All users (even filenames, which makes this a security risk)

### Expected behaviour
I would expect that activities within restricted folders only shows up for users with access to these folders

### Actual behaviour
Activities within restricted folders are visible to All users, exposing file and folders names of confidential data. (Access is restricted)

Is this a bug or intended?

**Comment by nickvergessen** [comment]
That is actually intended. The files access control does only block accessing files, see https://docs.nextcloud.com/server/stable/admin_manual/file_workflows/access_control.html#denied-access

Especially with time based rules or IP based rules, it is impossible to determinate if the user will be able to access the file or not. Also checking this on the fly all the time for all affected user would slow down the upload process too much.

**Comment by floriandusch** [comment]
Thanks for your reply.

It somewhat defeats the purpose of the App, imho. The intention of blocking access to a folder is to make it inaccessible and hide its content from users without the required permissions.

Seeing what kind of files get uploaded to a folder that I don't have access to increases the "criminal energy" manyfold, don't you think? It's a big security risk to your App.

Please re-consider your statement and add it the feature "hide from activity" as an enhancement.

**Comment by nickvergessen** [comment]
> It somewhat defeats the purpose of the App, imho. 

Well your usecase is just not what this was designed for. In your case you should just use seperate shares instead of a nested structure.

**Comment by floriandusch** [comment]
@nickvergessen Thanks for the information. The new ACL functionality in NC16 seems to be the right fit for us. :-)
