### ISSUE TITLE
Still possible to access accounts restricted to certain subnet 

### ISSUE THREAD

**Issue by codesmaker** [nextcloud/files_accesscontrol#128]
Hi,

First of all, thanks a lot for the nice and useful app.

I've noticed that if I restrict access to certain accounts to certain subnets, users would still be able to login and change settings for example. I can see that they aren't able to delete, edit, or create files/folders.

Here are the rules I set:
![file_access_control](https://user-images.githubusercontent.com/6999196/56271767-8b32db80-60f9-11e9-8e76-241ae791acaf.png)

What I expect is that users should not be able to login in the first place.

NC: 15.0.5
FIle access control: 1.5.0

**Comment by nickvergessen** [comment]
This app aims at "access controll for files" (see name).
It does not replace a server side firewall and also we don't aim to be one.
