### ISSUE TITLE
Restricted item can be selected and actions applied to it

### ISSUE THREAD

**Issue by emagri** [nextcloud/files_accesscontrol#137]
### Steps to reproduce
1. Create a folder AllItems. Create two folders XXXX and YYYY inside it
2. Create a hidden Reserved tag. Assign it to XXXX folder
3. Create a rule to restrict access to items with Reserved tag to user not belonging to Admins group

### Expected behaviour
When navigating to AllItems folder, a normal user will see XXXX and YYYY folder, but won't be able to enter XXXX folder. Any other access to XXXX (other than seeing it in the enclosing folder) should be blocked, giving an error

### Actual behaviour
When navigating to AllItems folder, a normal user will see XXXX and YYYY folder, but won't be able to enter XXXX folder. This is correct.
The problem: the user can select XXXX folder (alone or together with YYYY), and use the Actions button, for example to download the folders. The download succeeds and the resulting zip file contains all the XXXX folder and its contents

### Server configuration

Nextcloud 17.0.0

**Operating system**:
Linux 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64
**Web server:**
Apache/2.4.29 (Ubuntu) (apache2handler)
**Database:**
mysql 10.4.8
**PHP version:**

7.2.19-0ubuntu0.18.04.2 Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache
**Nextcloud version:** (see Nextcloud admin page)
17.0.0 - 17.0.0.9
**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**
``` Enabled: - accessibility: 1.3.0 - activity: 2.10.1 - admin_audit: 1.7.0 - bruteforcesettings: 1.4.0 - cloud_federation_api: 1.0.0 - comments: 1.7.0 - dav: 1.13.0 - federatedfilesharing: 1.7.0 - federation: 1.7.0 - files: 1.12.0 - files_accesscontrol: 1.7.0 - files_automatedtagging: 1.7.0 - files_pdfviewer: 1.6.0 - files_retention: 1.6.0 - files_rightclick: 0.15.1 - files_sharing: 1.9.0 - files_trashbin: 1.7.0 - files_versions: 1.10.0 - files_videoplayer: 1.6.0 - firstrunwizard: 2.6.0 - gallery: 18.4.0 - groupfolders: 5.0.4 - issuetemplate: 0.5.0 - logreader: 2.2.0 - lookup_server_connector: 1.5.0 - nextcloud_announcements: 1.6.0 - notifications: 2.5.0 - oauth2: 1.5.0 - password_policy: 1.7.0 - privacy: 1.1.0 - provisioning_api: 1.7.0 - recommendations: 0.5.0 - richdocuments: 3.4.2 - serverinfo: 1.7.0 - sharebymail: 1.7.0 - support: 1.0.1 - survey_client: 1.5.0 - systemtags: 1.7.0 - terms_of_service: 1.3.0 - text: 1.1.0 - theming: 1.8.0 - twofactor_backupcodes: 1.6.0 - updatenotification: 1.7.0 - user_ldap: 1.7.0 - viewer: 1.1.0 - workflowengine: 1.7.0 Disabled: - encryption - files_external ```
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "10.0.0.*" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "dbtype": "mysql", "version": "17.0.0.9", "overwrite.cli.url": "http:\/\/192.168.1.190\/nextcloud", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "mysql.utf8mb4": true, "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "maintenance": false, "ldapIgnoreNamingRules": false, "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory", "app_install_overwrite": [ "issuetemplate" ] } ```
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/77.0.3865.90 Chrome/77.0.3865.90 Safari/537.36
**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by emagri** [comment]
I saw that commit #17840 (backport of nextcloud/server#17822 to stable17, in milestone 17.0.1), should fix the problem.
Today I upgraded my server to 17.0.2 but in my opinion the problem still persists.

**Comment by blizzz** [comment]
please try https://github.com/nextcloud/server/pull/18488, this comes with 17.0.3

**Comment by emagri** [comment]
OK, thanks

Il giorno mar 14 gen 2020 alle ore 09:36 blizzz <notifications@github.com>
ha scritto:

**Comment by emagri** [comment]
In version 17.0.3 it works for me too :-)
Thanks
