### ISSUE TITLE
Enhancement: Add function to prevent sharing

### ISSUE THREAD

**Issue by Jan-NiklasB** [nextcloud/files_accesscontrol#139]
It would be very helpful to have the option to deny the sharing of files and / or folders tagged with a specific label.
The idea is, that you can give access to those files, but the users of the specified group can't share them. 
(For example for confidential documents)

**Comment by nickvergessen** [comment]
Well they could still reupload the file in another place and share it there? If you don't want people to reshare, do not use give them the re-sharing permission.

**Comment by Jan-NiklasB** [comment]
@nickvergessen 
Well, I would but at the moment I only know the option to disable resharing on the whole Server but not for defined groups and files/folders.

If this options already exists, please tell my where it can be found.

**Comment by nickvergessen** [comment]
Well it's not a global setting, but on a per share level. Just untick the first box in the `…` menu
> ![Bildschirmfoto von 2019-11-19 10-21-58](https://user-images.githubusercontent.com/213943/69133622-803c9100-0ab6-11ea-8739-b3ebcbf7115e.png)

**Comment by Jan-NiklasB** [comment]
Ah, okay after a bit of trying around, I figured it out....
I unset the checkbox at "allow re-share"...so this option isn't shown at all....

Sorry for stealing your time, maybe this "issue" will help someone who's nearly as blind as I :sweat_smile:
