### ISSUE TITLE
OnlyOffice/Collabora online can not download from a restricted folder

### ISSUE THREAD

**Issue by Vess19** [nextcloud/files_accesscontrol#140]
### Steps to reproduce
1. Set folder access restrictions
2. try to edit a document in the folder above using OnlyOffice/Collabora app, being logged as a user who has access to the restricted folder

### Expected behaviour
Open and edit a document in  OnlyOffice/Collabora

### Actual behaviour
no document is being uploaded in the OnlyOffice/Collabora browser window; Instead Error message  is shown in the nextcloud  log : 

'Exception: Call to a member function getUID() on null' , for the Collabora online app
'Download Not permitted: 11901901 ', for the OnlyOffice app 

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 17.0.1

**Where did you install Nextcloud from:**

**Signing status:**

`

**Comment by nickvergessen** [comment]
The reported version is EOL. If it still happens on a newer version feel free to create a new report.

**Comment by alderson59** [comment]
I have a similar issue - not sure if it is Collabora or File Access Control

https://github.com/nextcloud/richdocuments/issues/1168
