### ISSUE TITLE
Behavior changed in denied folders

### ISSUE THREAD

**Issue by gtchm** [nextcloud/files_accesscontrol#141]
**Steps to reproduce**

Install Groupfolder plugin and File Access Control plugin at version 1.6.0
Create an user and a tag
Configure all so that this user has not access to a specific folder inside the Groupfolder path

**Expected behaviour**

When trying to access this specific directory which has been tagged, the user should receive an error message and he would then be redirected to the root directory (this happened since NC 16.0.4 for sure, and possibly 16.0.5 aswell (I'm unable to test)

**Actual behaviour**

In NC 16.0.6, the user cannot see this directory anymore. 

**Operating system:**
Linux az-cs1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux

**Web server:**
nginx/1.10.3

**Database:**
10.1.26-MariaDB-0+deb9u1

**PHP version:**
PHP 7.2.7-1

My question is the following: is this a bug or something expected? If it will be like this also in the future versions, I kindly ask if it's possible to choose between the two behaviors, or in alternative to know which files are responsible for this change so I can compare the two versions and hopefully work to revert this behavior since it's not compatible to the current use of the NC product.

Thank you!

**Comment by nickvergessen** [comment]
Can you post a screenshot of your groupfolder configuration and your access control configuration?

**Comment by gtchm** [comment]
Hello, sure:
![Schermata1](https://user-images.githubusercontent.com/35197994/69907972-4f2a5d80-13e0-11ea-9537-38b1bf647d28.png)

![Schermata2](https://user-images.githubusercontent.com/35197994/69907974-53ef1180-13e0-11ea-832c-aa67793c343a.png)

**Comment by livier** [comment]
I Would also enjoy to know if the new comportment :
" the user cannot see the directory (and the file ?) when it is protected with File access Control rather than being prompt with an error and have redirection to root "
is the new way and will be maintained in the future. 
Contrary to gtchm, it is what I wich

**Comment by nickvergessen** [comment]
What are the advanced permissions you have set?

> is the new way and will be maintained in the future.

No, as that causes problems with the sync client as the checksums on folders do not match the provided content.

**Comment by gtchm** [comment]
> What are the advanced permissions you have set?

Hi Nick, unfortunately I had to rollback as required by my company so I cannot test right now. I'm willing to clone the vm on the weekend so I can replicate the issue and maybe give you guys access to the server if it's easier to troubleshoot this way. Please let me know and thank you so far for the interest.
Andrea

**Comment by nickvergessen** [comment]
The reported version is EOL. If it still happens on a newer version feel free to create a new report.
