### ISSUE TITLE
Option to allow shared folder to be accessed outside control

### ISSUE THREAD

**Issue by fengkaijia** [nextcloud/files_accesscontrol#145]
### Steps to reproduce
1. Share a folder via a link or email
2. Add a rule to block access if IP does not match **_A_**
3. Visit the shared link with IP **_B_**

### Expected behaviour
Can access the shared folder's file list and download is allowed.

### Actual behaviour
A page of the following error message is given: 

> File not found
> The document could not be found on the server. Maybe the share was deleted or has expired?

### Server configuration
**Nextcloud version:** 17.0.2

I understand server configuration is not needed as the actual behavior is the current expected behavior. But there are needs where access control is used to allow unauthorized access, yet still, allow sharing to other people outside the network (i.e. authorized access). Maybe an option can be added to the access rule, e.g. block access when "the file is not shared"?

**Comment by nickvergessen** [comment]
Put all users in one group and add a second check to your rule set:
Is not member of "all users" group

**Comment by fengkaijia** [comment]
@nickvergessen Thanks for the trick. FYI, the rule should be _Is_ a member of the group.
