### ISSUE TITLE
Guest Accounts are blocked from everything although they should not be affected by the set of rules

### ISSUE THREAD

**Issue by annievoss** [nextcloud/files_accesscontrol#154]
### Steps to reproduce
1. Create a guest account and share a folder (subfolder of a groupfolder) with it
2. Create two usergroups A and B and admin group all three containing normal users
3. Create a groupfolder with all three groups have permissions to write, share an delete
4. Create a folder with a subfolder and set a tag on the subfolder: "exclusively for usergroup a and admin" wich users can see but not change
5. Create a set of rules for accesscontrol with
     a) "File system tag" is tagged with "exclusively for usergroup a and admin"
     b) "usergroup membership" is not a member of "usergroup A"
     c) "usergroup membership" is not a member of "admin"

### Expected behaviour
All users should see the groupfolder and the parent folder but only members of usergroup A and admin group get access to the subfolder. Usergroub B members should either not see the subfolder at all or  be able to klick on it but can't see what is in it (preferably not by kicking them back to root without any warnings, but that's another issue). The guest user shouldn't be affected at all because the shared folder is not even near to the restricted folders, doesn't have a tag and the guest ist not part of a usergroup at all (except "invisible" guest group by default).

### Actual behaviour
Users in usergroup A and admin can use the folder as expected. Members of usergroup B can't see the folder at all and guest user tries to klick on the shared folder and is kicked back to root with warning: "Operation is not allowed" or something like that. Also other groupfolders which the guest user was able to see are not visible there anymore.

### Server configuration
**Nextcloud version:** 17.0.3

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here:
-> No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - announcementcenter: 3.6.1
  - apporder: 0.9.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - deck: 0.8.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_automatedtagging: 1.7.0
  - files_fulltextsearch: 1.3.6
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - forms: 1.1.0
  - fulltextsearch: 1.3.8
  - fulltextsearch_elasticsearch: 1.4.1
  - groupfolders: 5.0.5
  - guests: 1.3.1
  - impersonate: 1.4.0
  - issuetemplate: 0.6.0
  - keeweb: 0.6.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.2
  - notes: 3.1.5
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - occweb: 0.0.7
  - onlyoffice: 4.1.4
  - password_policy: 1.7.0
  - polls: 1.3.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - support: 1.0.1
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - user_usage_report: 1.1.2
  - viewer: 1.2.0
  - workflow_script: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - encryption
  - federation
  - files_accesscontrol (of course enabled when trying but the guest user hast work to do)
  - files_external
  - gallery
  - recommendations
  - survey_client
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "79.133.48.127",
            "nevb.qloc-cloud.de",
            "office.nevb.qloc-cloud.de",
            "nevb.qloc-cloud.de",
            "community.vcp-mitteldeutschland.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "https:\/\/community.vcp-mitteldeutschland.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "integrity.check.disabled": "true",
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "logtimezone": "Europe\/Berlin",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "app_install_overwrite": [
            "occweb"
        ]
    }
}

**no external storage used**

**no encryption is used**

**No external user-backend is used**

**Comment by nickvergessen** [comment]
> Create a set of rules for accesscontrol with

This sounds like the point where things go wrong. Make sure to use one rule group only:
> ![Bildschirmfoto von 2020-03-11 09-44-49](https://user-images.githubusercontent.com/213943/76398951-122a1b80-637e-11ea-975a-500fb7c4535d.png)

Then it works fine here.
