### ISSUE TITLE
Upload file not blocked

### ISSUE THREAD

**Issue by mkula70** [nextcloud/files_accesscontrol#162]
### Steps to reproduce
1. Create a File access rule to block .php file
2.  Select File MIME type - application/x-php
3. Or Select File MIME type - /^application\/(php|x-php)$/i
4. Upload .php file

### Expected behaviour
Error message indicating File is Blocked

### Actual behaviour
The .php file is uploaded to Nextcloud

### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 19.0.0

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - analytics: 2.4.1
  - apporder: 0.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - dashboard: 6.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_antivirus: 2.4.1
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_fulltextsearch: 1.4.3
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - fulltextsearch: 1.4.2
  - fulltextsearch_elasticsearch: 1.5.2
  - gridbright: 0.0.1
  - gridbright_audit: 0.0.1
  - gridbright_dashboard: 0.0.1
  - gridbright_mail: 0.0.1
  - groupfolders: 7.0.0
  - groupquota: 0.1.2
  - guests: 1.4.6
  - limit_login_to_ip: 3.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - maps: 0.1.6
  - metadata: 0.12.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.3.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - ransomware_detection: 0.8.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - terms_of_service: 1.5.1
  - text: 3.0.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflow_pdf_converter: 1.4.0
  - workflow_script: 1.4.0
  - workflowengine: 2.1.0
Disabled:
  - contactsinteraction
  - dashboardcharts_server
  - files_external
  - firstrunwizard
  - mail
  - spreed
  - user_ldap
**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpass": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "adminlogin": "admin",
        "adminpass": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": 443,
                "use_ssl": true,
                "use_path_style": true,
                "region": "***REMOVED SENSITIVE VALUE***"
            }
        },
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "19.0.0.12",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "mysql.utf8mb4": true,
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "dashboard",
            "dashboardcharts",
            "ransomware_detection",
            "fulltextsearch",
            "files_fulltextsearch",
            "fulltextsearch_elasticsearch",
            "gridbright_dashboard"
        ],
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "America\/New_York",
        "log_query": false,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "auth.webauthn.enabled": false,
        "skeltondirectory": "***REMOVED SENSITIVE VALUE***",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "onlyoffice": {
            "verify_peer_off": true
        },
        "theme": ""
    }
}


**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 80.0 64-bit
**Operating system:**
windows 10
### Logs

**Comment by nickvergessen** [comment]
The correct mimetype is `text/code`
