### ISSUE TITLE
blocking mimetypes is not working with shared folders

### ISSUE THREAD

**Issue by lug-gh** [nextcloud/files_accesscontrol#168]
### Steps to reproduce
1. restrict mime types to whatever you want to upload
2. share a folder with a group
3. login as a user in that group and place a file in the folder

### Expected behaviour
user should be able to place files in the shared folder

### Actual behaviour
user in the group cant place files in the shared folder

### Server configuration
**Operating system**: Ubuntu 18.04.5 LTS

**Web server:** apache2

**Database:** 10.1.44-MariaDB

**PHP version:** 7.3

**Nextcloud version:** 19.0.3

**Where did you install Nextcloud from:** source, but updated from 17 or 16

**Signing status:** 

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** doesnt matter, chrome, firefox or even windows network drive via webdav

**Operating system:** doesnt matter

#### Nextcloud log (data/owncloud.log)
```
nothing new is written if i upload a file
```

#### Apache Log
```
*myip* - - [10/Sep/2020:14:05:42 +0200] "PROPFIND /remote.php/dav/files/*myusername*/desktop.ini HTTP/1.1" 404 7157 "-" "Microsoft-WebDAV-MiniRedir/10.0.18363"
*myip* - - [10/Sep/2020:14:05:45 +0200] "PUT /remote.php/webdav/Projekt%20Test/test.pdf HTTP/1.1" 201 1541 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
*myip* - - [10/Sep/2020:14:05:45 +0200] "PROPFIND /remote.php/dav/files/*myusername*/Projekt%20Test/test.pdf HTTP/1.1" 207 2001 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
*myip* - - [10/Sep/2020:14:05:45 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php HTTP/1.1" 200 1607 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"
*myip* - - [10/Sep/2020:14:05:46 +0200] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FProjekt%20Test HTTP/1.1" 200 1051 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36"

```

The shared folder is named "Projekt Test", the file I want to upload is "test.pdf"
If I disable files_accesscontrol or delete my ruleset everything works, it also works if I use a folder I created myself, not a folder i got shared.

![image](https://user-images.githubusercontent.com/24546639/92727300-2a034c00-f36f-11ea-82aa-99fc74808321.png)

The problem already existed on nextcloud 18 and the older files_accesscontrol version

**Comment by nickvergessen** [comment]
Is it only pdfs, or are all uploads failing for you?

**Comment by lug-gh** [comment]
Forgot to mention, it's for all filetypes, png, jpeg.
I didn't try to create a folder though, but that will probably fail too.

**Comment by lug-gh** [comment]
@nickvergessen can you confirm this bug?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/files_accesscontrol/pull/173 fixes it?

**Comment by lug-gh** [comment]
It's working via Webinterface now, not via webdav though.

By the way, I applied that fix manually. Is it safe to do so, or will there be an update to 1.9.2?

**Comment by nickvergessen** [comment]
yeah there will be an update to 1.9.2 and until then patching it manually is okay to do.

**Comment by lug-gh** [comment]
Okay. Should I open a new issue or why did you close it?

**Comment by nickvergessen** [comment]
The problem is fixed, just a release missing and we don't need an issue open for that.

**Comment by lug-gh** [comment]
Well, I said it's working via Browser after the fix, via webdav it's not working.
Thats why I asked if I should open a new ticket for webdav, or if that should be done here.

**Comment by nickvergessen** [comment]
Ah, missed that line. Well when it's a non-shared directory its a different issue. In that case yeah please open a new issue
