### ISSUE TITLE
Block user agent /Microsoft-WebDAV-MiniRedir\/

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/files_accesscontrol#176]
hi on acl i do regex to block user agent my regex is : 
/Microsoft-WebDAV-MiniRedir\/10.0.18362/

I reality i want block all User agent contain Microsoft-WebDAV-MiniRedir but it's not working. 
What i'm doing wrong
Thx

**Comment by nickvergessen** [comment]
try `/Microsoft-WebDAV-MiniRedir\/[\d\.]+/i`

**Comment by tanguy-opendsi** [comment]
Hi @nickvergessen  thx for your reply but it's not working :/ . 
But if we test your regex on regex101.com it's working.

**Comment by nickvergessen** [comment]
Then maybe check your accesslog or nextcloud log for the real complete user agent

**Comment by tanguy-opendsi** [comment]
@nickvergessen This is what i did and it's the exact user agent name. 
In your regex you only test the dot . after / it's possible to include every char/number after / 
Best regards

**Comment by nickvergessen** [comment]
Adjusted above
