### ISSUE TITLE
Access control not respected in android app

### ISSUE THREAD

**Issue by gpz1100** [nextcloud/files_accesscontrol#192]
### Steps to reproduce
1. Folder's access is limited in scope to private ip (10.10.0.0/16)
2.
3.

### Expected behaviour
Using browser on local lan this flow is respected.  Using vpn to test, folders that should not be viewable are blocked properly.

### Actual behaviour
In android app (3.15RC), folder has full access.  ****EDIT*** Correction, it will list the files but won't allow them to be opened.  Viewing through vpn/webbrowser, one can't even enter the folder to see file listing.  I'm not sure if this is a collaborative tags app issue or android app issue¿?

### Server configuration

**Operating system**:
ubuntu 20
**Web server:**
apache
**Database:**
postgres
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
20.0.8
**Where did you install Nextcloud from:**
hansson vm
**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

Yes and no.  Issue is with local folder.  For external (smb) folder this rule is properly respected.

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

![image](https://user-images.githubusercontent.com/1902753/109431981-af86c100-79ce-11eb-991f-785d9e6a5027.png)

**Comment by nickvergessen** [comment]
I guess the mobile app caches the dir list for performance issues.

But then again as per https://docs.nextcloud.com/server/21/admin_manual/file_workflows/access_control.html#denied-access
Directory listing is not in target of this app and there are otherways to find out if a file exists. It can therefor only prevent access of such items but not listing.

**Comment by gpz1100** [comment]
Understood.  Can the access_control be extended to include folders too?

I also have a local external mount configured which has the same tag/access control assigned.  It doesn't show up at all in both web viewing and android app.

**Comment by nickvergessen** [comment]
Well external storages are not mounted when read permissions are not there. But there is no permission for "listing".
It's been reported ever now and then, but unlikely to change
