### ISSUE TITLE
Feature synchronisation group user in Nextcloud Files Access Control App

### ISSUE THREAD

**Issue by OlivierDoucet** [nextcloud/files_accesscontrol#198]
### Steps to reproduce
I use Nextcloud and Files Access Control App Flux addon (files_accesscontrol: 1.10.2).
Users groups are in LDAP data base
When I add a new users groups this one is synchronised in Nextcloud, but it is not visible in Files Access control App combo box
Thank you for your help

### Expected behaviour
For example the users group G21_VOIT_PAS_RESTRICTION is added in LDAP database
![image](https://user-images.githubusercontent.com/77565994/118396364-8f6eb180-b64f-11eb-87a1-b1b33a7435fd.png)
This group is visible in Nextcloud (Users menu) 
![image](https://user-images.githubusercontent.com/77565994/118396446-dbb9f180-b64f-11eb-9a5f-11fb419d9991.png)

But this group is not visible in combobox of Files Access Control App
![image](https://user-images.githubusercontent.com/77565994/118396616-95b15d80-b650-11eb-915b-98d0e1e0203e.png)

All groups added after the first installation of Nextcloud are missing.

### Server configuration

**Operating system**: DEBIAN 10 Linux 4.19.0-16-cloud-amd64 x86_64

**Web server:** Intel Core Processor (Haswell, no TSX) (8 cores) 16G0

**Database:** MySQL

**PHP version:** 7.3.24

**Nextcloud version:** 20.0.8
**Where did you install Nextcloud from:** docker

**List of activated apps:**

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - announcementcenter: 4.0.1
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - carnet: 0.23.8
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - drawio: 1.0.0
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_linkeditor: 1.1.5
  - files_markdown: 2.3.3
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.4
  - groupfolders: 8.2.0
  - ldap_contacts_backend: 1.0.1
  - ldap_write_support: 1.2.1
  - ldapcontacts: 2.0.5
  - login_notes: 0.4.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - occweb: 0.0.7
  - onlyoffice: 6.3.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.8.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.23.1
  - spreed: 10.0.7
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - welcome: 0.0.5
  - whiteboard: 0.0.3
  - workflowengine: 2.2.0

**Nextcloud configuration:**
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.intra.gresi21.fr"
        ],
        "trusted-poxies": [
            "swag"
        ],
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/nextcloud.intra.gresi21.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "occweb",
            "ldapcontacts",
            "ldaporg"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "session_lifetime": 3600,
        "session_keepalive": false
    }
}

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** OpenLDAP

### Client configuration
**Browser:** no matter

**Comment by blizzz** [comment]
not all groups are loaded at once. type for search.

**Comment by OlivierDoucet** [comment]
Thank you blizzz but what do you mean by "type for search" ?

**Comment by blizzz** [comment]
press the first few letters of the group name on your keyboard :)

**Comment by OlivierDoucet** [comment]
Thank you for your help
