### ISSUE TITLE
Configured flows not fully displayed in admin section

### ISSUE THREAD

**Issue by manu-p** [nextcloud/files_accesscontrol#207]
Hi,

The following screenshot shows “Select option” for the two last User group membership. 
See [here](https://imgur.com/a/mNrQp7X).

When I check in the DB tables, I can see these 2 last fields are valued to the initialy entered values.

So I guess, the flow must be working accordingly to what the author expects.
But, we reckon it’s not normal we can’t see the values in these 2 fields since they are in the oc_flow_checks and _operations tables rows.
Can't manage these flows.

What’s wrong?

### Server configuration
**Operating system**: Ubuntu 18.04.5

**Web server:** apache 2.4.29

**Database:** Mysql 5.7.35

**PHP version:** 7.4.21

**Nextcloud version:** 20.0.9

**File access control version:** 1.10.2

**Comment by manu-p** [comment]
Hi, am I the only one to experience this? 

Is this not a bug?

**Comment by ivgo** [comment]
No

**Comment by manu-p** [comment]
Hi,

We're still facing this behavior, do you answer No to "am I the only one to experiencethis?" or to "Is this not a bug?".

**Comment by manu-p** [comment]
Or was it just a joke @ivgo?

Now its just the same with NC 21.0.4 and File Access Control 1.11.0.

Anyone to take this into account?

**Comment by nickvergessen** [comment]
> From now on, I suggest my users and customers to avoid using this app for there's no one to take questions and bugs into account...

If you have customers, maybe you can get a subscription so we can prioritize your input.

> The following screenshot shows “Select option” for the two last User group membership.
> See [here](https://imgur.com/a/mNrQp7X).
> 
> When I check in the DB tables, I can see these 2 last fields are valued to the initialy entered values.
> 
> So I guess, the flow must be working accordingly to what the author expects.

My assumption is that the groups no longer exist and therefore the options are not longer offered.
Could also be that there was a problematic character in the option (/ or " or # or something alike) which the UI could not handle.
In that case retesting with the newest version could be helpful, as the UI library was replaced in the meantime.

If the bug still persists, please report it over at https://github.com/nextcloud/server/issues/new/choose for the workflow engine as files access control is not in charge of the checks/rules but only the operation.
