### ISSUE TITLE
Strange (and wrong) behavior with xml (and other) files using mimetype filtering because of partial upload (*.part - files!!)

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/files_accesscontrol#233]
### Steps to reproduce
1. crete flow for file access control with several rules including
2. mime type xml (so that a specific user group is allowed to access xml files (and other files like pdf, docx or dxf)
3. try to upload xml file

### Expected behaviour
xml file is uploaded and the user is able to work with it online or download it...

### Actual behaviour
access denied

### Server configuration

**Operating system**:
ubuntu
**Web server:**
apache
**Database:**
mysql
**PHP version:**
8.0
**Nextcloud version:** (see Nextcloud admin page)
23.0.2

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
No errors have been found.
```

**List of activated apps:**
occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - encryption: 2.11.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0

**Workaround:**
allow filename /.*\.part$/
...but ... this can not!!! be a solution!!!

**Comment by nickvergessen** [comment]
Works fine with this rule:

`File MIME type` => `is` => `application/xml`
