### ISSUE TITLE
Versions of files can be downloaded

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/files_accesscontrol#25]
1. Create a rule that only members of the group admin can access or write files
2. As admin create a test file, create multiple versions of it
3. Share the file with a regular user
4. As regular user download the version

=> This should not work. But does.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Same with trashbin I guess...

**Comment by nickvergessen** [comment]
One problem with that is, that tags are different for versions and trashbin. I will have a look what we can do against this.
