### ISSUE TITLE
Add support for individual IPs

### ISSUE THREAD

**Issue by toxpal** [nextcloud/files_accesscontrol#258]
I use NC for small business needs. To ensure people can only access files from office computers, I manually added list of allowed IPs to .htaccess file, but the problem is that NC restores original .htaccess during every upgrade, so I decided to use Files Access Control instead.

Unfortunately, the app doesn't support individual IPs, so I can't limit file access to specified computers in the office. And then there's no point to use the app, because it can't control file access really strictly. Is there a reason why such feature is not supported and can it be implemented?

**Comment by blizzz** [comment]
So the "Request remote address" does not suit your needs?

**Comment by toxpal** [comment]
It does not allow individual IP to be entered, it expects whole range, as explained in the documentation:

> Request remote address: An IP range (either v4 or v6) for the accessing user

**Comment by blizzz** [comment]
It should be achievable with a netmask specifying just one address in this range: a.b.c.d/32

**Comment by toxpal** [comment]
Thank you. Will try and let you know.

**Comment by toxpal** [comment]
It works, issue solved!
