### ISSUE TITLE
Images can still be accessed via gallery / Preview images are still shown

### ISSUE THREAD

**Issue by Florz** [nextcloud/files_accesscontrol#30]
1. create access group:
    a) File system tag is tagged with "private"
    b) Request user agent is not Desktop client
2. tag a folder as "private"
3. enter folder via web interface
-> you will see preview images for text files and images (e.g. *.jpg)

4. click on any image file with a prview image
-> full version is shown
-> other files are protected

=> directory listing should not be possible
=> other apps must not provide access to protected files

**Comment by nickvergessen** [comment]
Directory listing is not what this app is about, that would be awesome, but is waaaay to complicated to achieve.

I noticed the preview problem already in https://github.com/nextcloud/files_accesscontrol/pull/28#issue-172404105
But I forgot that the gallery displays 2k thumbnails. Will have a look how we can hack in some protection here.

**Comment by nickvergessen** [comment]
@Florz can you tests https://github.com/nextcloud/files_accesscontrol/issues/30 + https://github.com/nextcloud/server/issues/1089
Thanks!

**Comment by Florz** [comment]
@nickvergessen works for me, fixed. Thanks!

**Comment by MorrisJobke** [comment]
Hey @Florz, nice to see you here! Chemnitz dudes FTW 😄
