### ISSUE TITLE
Collaborative tags cannot be found

### ISSUE THREAD

**Issue by PEisenbarth** [nextcloud/files_accesscontrol#300]
### Steps to reproduce
1. Search in an access control flow for a collaborative tag that is different to the five suggested tags in the dropdown

### Expected behaviour
The searched tag should appear in the dropdown and should be choosable

### Actual behaviour
The searched tag isn't shown and can't be chosen

### Server configuration
**Operating system**: Linux 4.4.180+ aarch64

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** 8.0

**Nextcloud version:** 25.0.1

**File access control version:** 1.15.1

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

**Comment by markus-gitdev** [comment]
Can confirm, that the issue is also present with nextcloud version 25.0.2, file access control version 1.15.1 and collaborative tags version 1.15.0.

**Comment by chrissi55** [comment]
same here
all my flow files_accesscontrol items don't show which tags i have used during creation of a rule.

maybe same issue that nextcloud can't list more than 5 tags in a pulldown since change between 24.0.x and 25.0.x versions.

**Comment by benmprojects** [comment]
Why has this not receive any update. This is a critical part of nextcloud. Is this dead?

**Comment by benmprojects** [comment]
@nickvergessen any update. Please

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/36754

**Comment by nickvergessen** [comment]
> Is this dead?

It's not. but the broken part is not within my working scope (I still debugged it recently and suggested a fix)

**Comment by benmprojects** [comment]
@nickvergessen do you have a link to the issue?

**Comment by nickvergessen** [comment]
![Bildschirmfoto vom 2023-02-24 10-17-41](https://user-images.githubusercontent.com/213943/221140157-52abff7d-fe6c-4eda-8238-15763876e5a8.png)

**Comment by benmprojects** [comment]
Sorry my joke was not very good :)..

Thanks for working on this guys. I am still happy to put up a bounty for this.

**Comment by nickvergessen** [comment]
Feel free to review the pull request, then we can get it in:
https://github.com/nextcloud/server/pull/36754
