### ISSUE TITLE
file mime type with (is not) dosent work 

### ISSUE THREAD

**Issue by ghost** [nextcloud/files_accesscontrol#311]
### Steps to reproduce
![image](https://user-images.githubusercontent.com/49244741/222376067-90876f50-cb8e-47f0-a874-e10d4e6fe371.png)

### Expected behaviour
users who aren admins cant upload other than .exe files

### Actual behaviour
They cant upload any thing 
![image](https://user-images.githubusercontent.com/49244741/222376360-ab9cfc80-ebc5-4470-ac5b-1884a45b753e.png)
- Operation is blocked by access control was for exe file
- An unknown error has occurred was for other files

note :
![image](https://user-images.githubusercontent.com/49244741/222376788-6d8c4743-5b1b-4917-8b3b-d1953f74d9b5.png)

this do work as intended 
### Server configuration

**Operating system**:
debian 11
**Web server:**
nginx
**Database:**
mariadb
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
25.0.4
**Where did you install Nextcloud from:**
manually

**Comment by nickvergessen** [comment]
Closing issue from a ghost account.
If anyone else has the same issue please create a new one.
