### ISSUE TITLE
File picker throws 500 when selecting a blocked file

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/files_accesscontrol#32]
Found while testing https://github.com/nextcloud/server/pull/1135

### Steps to reproduce
1. Use the file picker (avatar upload from files)
2. Select a blocked image

### Expected behaviour
403 

### Actual behaviour
500

**Comment by MorrisJobke** [comment]
@nickvergessen Status of this? Crucial for 10.0.1?

**Comment by nickvergessen** [comment]
Crucial: No
Papercut: Yes

**Comment by MorrisJobke** [comment]
Okay ... then move this to 10.0.2
