### ISSUE TITLE
v1.16.0 is missing code signatures

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/files_accesscontrol#346]
No `appinfo/signature.json`.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud-releases/files_accesscontrol/actions/runs/4198322264/jobs/7281789502#step:19:231

>  Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty".files_accesscontrol/

👀

**Comment by nickvergessen** [comment]
Reopening for follow up release reminder

**Comment by nickvergessen** [comment]
Worked now for 1.15.2 and 1.16.1
