### ISSUE TITLE
On restricted files I can delete the tags and so I have permission for file access.

### ISSUE THREAD

**Issue by thomaskor** [nextcloud/files_accesscontrol#388]
### Steps to reproduce
1. AddOn File Access Control
2. Set Tags for an file
3. login as restricted user
4. chlick on the file -> you haven't access
5. go to details and remove the tags
6. you have access

### Expected behaviour
not possible to delete tags on files details, which tags as user I haven't set

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
It is recommended to use restricted or invisible tags for the block rules only and then they can only be removed by administrators

**Comment by Nils160988** [comment]
Closing, as the use of restricted/invisible tags is explicitly mentioned in the documentation (https://docs.nextcloud.com/server/latest/admin_manual/file_workflows/access_control.html), so this is no bug here.
