### ISSUE TITLE
Please release v1.15.2 and v1.16.1

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/files_accesscontrol#407]
https://github.com/nextcloud/files_accesscontrol/pull/343 is preventing moving shares if files_accesscontrol is active.

This is fixed already but the fix has not been released.

This is still open as a reminder. Not sure what that means: 
* https://github.com/nextcloud/files_accesscontrol/issues/346

**Comment by nickvergessen** [comment]
Done
