### ISSUE TITLE
restriction based on tags not only applies to tagged folder but also to its first ascendant.

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/files_accesscontrol#421]
### Steps to reproduce
1. As an admin, create a group `grouptest`, a restricted tag `tagtest`.
2. Create the following folder structure and apply the tag `tagtest` on `level 3`:
- `level 1`
  - `level 2`
    - `level 3 (tagtest)`
4. create a file access control rule as follow: if folder is tagged with `tagtest` and user is not member of `grouptest` then block access to the file
5. share the `level1` folder with `Bob` who is NOT member of `grouptest`
6. As `Bob`, go into `level 1` folder.
7. Try to go inside `level 2` folder

### Expected behaviour
Bob should be able to go inside `level 2`, and should see `level 3` greyed out

### Actual behaviour
Going into `level 2` raise a forbidden operation error to Bob.

The main issue is that if Bob should access data inside level 2 folder other than the level 3 folder, he can't anymore :/

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 27.1.0

**Where did you install Nextcloud from:**
t.nc.c

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Definitely a regression and not meant to be that way. But can confirm.

My home instance is not usable anymore because I have a blocked folder in my root.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/40473

**Comment by nickvergessen** [comment]
Let me try to write an integration test to test this in the future with this app here
