### ISSUE TITLE
Remove ability to download files

### ISSUE THREAD

**Issue by greavette** [nextcloud/files_accesscontrol#45]
Not sure where to put this suggestion/question so I'll try it here.

Is there  a way to limit the download access for files/users/groups using this app?

Thank you.

**Comment by nickvergessen** [comment]
Yes, that is exactly what it does
https://docs.nextcloud.com/server/10/admin_manual/configuration_files/files_access_control.html

**Comment by greavette** [comment]
Thank you @nickvergessen for this quick reply!  

Where can I ask more questions about how to use this app?  Here on GitHub or in the forums?

Thank you.

**Comment by nickvergessen** [comment]
Depends on what kind of questions you have.

**Comment by greavette** [comment]
Hello @nickvergessen 

I'm looking for an example of setting a group to be able to read (view) documents (PDF in my case) from a shared folder but they can't download it (or do anything else...ideally I don't want them to be able to download, print, upload or anything else under their account).  I have documents some of our employees at a workstation will reference but they have no need to download the PDF documents or do any other work/sharing on documents in their roles.

I setup a shared folder with my Admin Account and I setup a non-admin user account in their own group called generaluser.  Using the File Access Control I'm looking for how to allow anyone in my 'generaluser' group to see the files shared by the admin but they can't download those files).

I know this kind of goes against what NextCloud is for...but for my users that do use documents they will not be part of the 'generaluser' group...the generaluser group employees are not working on documents in their job.

Can File Access Control help me in what I'm looking to do?

Hopefully I've explained myself in enough detail.  Thank you in advance for any assistance you can provide.

**Comment by nickvergessen** [comment]
Sorry, but there is no way to identify whether a user is "downloading" or "viewing" a file. Viewing the file already downloads it, otherwise users are unable to view anything.

Also the access control is an "all or nothing" solution. So this is and will not be possible.

**Comment by greavette** [comment]
Drat!  :)  Thank you for the reply @nickvergessen Joas...I was hoping to have finally found an easy way to use NextCloud as a PDF viewer for our small. office.  I still see a benefit to using File Access Control to not share files outside the office.  I'll keep digging into the code to see how I can remove the download button.

Thank you for your time in answering my questions.
