### ISSUE TITLE
TextEditor App showing wrong file to edit using .docx

### ISSUE THREAD

**Issue by g33kphr33k** [nextcloud/files_accesscontrol#48]
### Steps to reproduce
1.  Edit .docx file in TextEditor App
2.  
3.

### Expected behaviour
Latest version of document should be shown

### Actual behaviour
Old version shown on all PCs.  If you open from sync client or download via browser then correct version is available.

### Server configuration
**Operating system**:  Debian Jessie

**Web server:**  Apache/2.4.10 (Debian) OpenSSL/1.0.1t

**Database:** mariadb-server-core-10.0 amd64 10.0.28-0+deb8u1

**PHP version:**  PHP 5.6.27-0+deb8u1

**Nextcloud version:** 10.0.1 Stable

**Where did you install Nextcloud from:** nextcloud download site

**Signing status:**  

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - external: true
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_accesscontrol
  - templateeditor
  - user_external
  - user_saml

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "ocjamrz7m4lf",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ownclouduk.argonon.com",
            "ownclouduk.argonongroup.ltd"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "http:\/\/ownclouduk.argonon.com",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_from_address": "postmaster",
        "mail_domain": "argonon.com",
        "mail_smtphost": "10.1.5.13",
        "mail_smtpport": "25"
    }
}
**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:**  Any (tested on Firefox and Chrome)

**Operating system:**  Windows 7 and Linux

#### Nextcloud log (data/owncloud.log)
{"reqId":"UsI+6YUoA8aQmqa\/Nvi\/","remoteAddr":"10.1.4.190","app":"core","message":"Could not get categories: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:40+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=0","user":"Karl.Dawkins"}
{"reqId":"UsI+6YUoA8aQmqa\/Nvi\/","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:40+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=0","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get categories: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:41+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:41+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:41+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:42+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:42+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:42+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:43+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}
{"reqId":"Ylu95SlAwl\/u0H9EgU3u","remoteAddr":"10.1.4.190","app":"core","message":"Could not get application: cURL error 60: SSL certificate problem: unable to get local issuer certificate","level":3,"time":"2016-11-22T11:28:43+00:00","method":"GET","url":"\/index.php\/settings\/apps\/list?category=enabled&includeUpdateInfo=1","user":"Karl.Dawkins"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
Well that's an issue with the documents/texteditor app you are using.
Please report the issue to them
