### ISSUE TITLE
Files Access Control not showing Access Control based on "Collaborative Tags"

### ISSUE THREAD

**Issue by kichilron** [nextcloud/files_accesscontrol#53]
### Steps to reproduce
1. Coll. Tags and File Access Control are both activated
2. Trying to set a rule in File Access Control doesn't show rules based on Coll. Tags

### Expected behaviour
I should be able to set file access control rules based on the collaborative tags.

### Actual behaviour
This setting is not showing up in the dropdown menu: http://i.imgur.com/4MBCrms.png
Maybe I'm being thick, but I didn't found much of any documentation, but the one I found on the official site was showing entirely different rulesets to choose from.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server**: Apache

**Database:** MySQL

**PHP version:** 7.0.8

**Nextcloud version:** 10.0.1

**Where did you install Nextcloud from:** NextCloud Website

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
```

**The content of config/config.php:**

```
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome / Mozilla / doesn't matter

**Operating system:** Windows 10

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
`File system tag` is what you are looking for.

**Comment by kichilron** [comment]
Very well, it was just a bit confusing to me.
Thank you for your quick response.
