### ISSUE TITLE
Image Preview in Memories available for blocked file

### ISSUE THREAD

**Issue by ManfredWisniewski** [nextcloud/files_accesscontrol#543]
### Steps to reproduce
1. block access to a file
2. open the memories app (timeline, map etc.)
3. image previews are shown, if you click on one the image is displayed but then gets removed
this affects the preview on the map as well as on the right hand timeline

### Expected behaviour
No preview should be available

### Actual behaviour
previews of blocked files are displayed

In this example all the files from Sat, May 25 are in a directory that is blocked for the user.
Image no1: preview available
![image](https://github.com/nextcloud/files_accesscontrol/assets/13734031/a6e9ad0d-db40-4b94-a65b-cf748ebbeb3a)
Image no2: image loading with preview in the background
![image](https://github.com/nextcloud/files_accesscontrol/assets/13734031/21d02219-511e-41d8-91dc-b71d7f9f428e)
Image no3: image gets removed when loading finishes
![image](https://github.com/nextcloud/files_accesscontrol/assets/13734031/d82fd42a-5112-43bf-866a-ee4d4ba8a990)

**Comment by nickvergessen** [comment]
Are you sure they are not just cached in your browser?
This app works on Storage layer level. We don't actually care how or which app is loading an image.
If that is still a real issue, the memory app would be doing some real deep hacking/working around.

**Comment by ManfredWisniewski** [comment]
> Are you sure they are not just cached in your browser? 
You are correct! I tested it with a clean cache for the user that has no access and he can only see the default thumbnail icon - no preview. _Not a real issue._
Thanks!
