### ISSUE TITLE
Denied file listed whe filtering by Tag

### ISSUE THREAD

**Issue by mailings** [nextcloud/files_accesscontrol#57]
### Steps to reproduce
1.Create a folder tree with a root folder (Root), below that folder create two subfolders (Folder1, Folder2)
2.Create a file access control rule that denies access to Folder 1 to users not belonging to Group1
3.Place a file in Folder1 with a Tag (Etiqueta)
4.Share the Root folder with a user not belonging to Group1 (UserX)
5.Login as UserX and filter By tag "Etiqueta"

### Expected behaviour
Files not accesible by access control should not be found when filtering using Tags

### Actual behaviour
File is listed in results, however not accesible

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Comment by nickvergessen** [comment]
As per the docs, listing is nothing this app can protect against:
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/files_access_control.html#denied-access

This is due to technical limitations.
