### ISSUE TITLE
File access controll -> cannot create new folders! 

### ISSUE THREAD

**Issue by tuxi73** [nextcloud/files_accesscontrol#58]
### Steps to reproduce
Hello,

i created a rule that our Users only can Upload .gif files
"File mime type" "is not" "image/gif"

This rule works fine for us, but Users cannot create new folders.
The Message is "Could not create [Foldername]".

So I add this rule:
"File mime type" "is not" "httpd/unix-directory"

But this doesn't work. User become the same Error-Message.

What's the Problem ?

Regards
Alex.

**Comment by nickvergessen** [comment]
Can you test https://github.com/nextcloud/server/pull/4010/files please

**Comment by tuxi73** [comment]
Perfect now it works ! Great Job !

**Comment by nickvergessen** [comment]
Lets keep this open until the fix is merged.

**Comment by tuxi73** [comment]
The next Problem with the App.
I shared a folder by link with "Allow upload and editing".
The Recipient of the Link can not upload Files into the share. 
Error Message "Forbidden". If i disable the App everything is ok.

**Comment by nickvergessen** [comment]
Can you please post a full screen of your rules?

**Comment by tuxi73** [comment]
Here it is ....
![rules](https://cloud.githubusercontent.com/assets/26601873/24254616/aaf61432-0fe3-11e7-8140-1c20e11c6669.jpg)

**Comment by nickvergessen** [comment]
Works here
