### ISSUE TITLE
File Access Control not matching mime-type

### ISSUE THREAD

**Issue by alexisit** [nextcloud/files_accesscontrol#68]
### Steps to reproduce
1. Configure a file access control rule based on mime-type. For exemple mime-type matching `/^image\//i`
2. Create a share and try to upload a jpeg file. It will fail.
3. Now change the jpeg file extension to something that doesn't match the rule we create. For exemple file.exe. It will succeed.

### Expected behaviour
The expected behaviour is that "mime-type matching" really match the mime-type.

### Actual behaviour
Mime-type metching seems to only care about the file extension and not the file's mime-type.

### Server configuration

**Operating system:** Debian 8.8

**Web server:** Apache/2.4.10

**Database:** MariaDB/10.0.30

**PHP version:** PHP/5.6.30

**Nextcloud version:** 12.0.0

**Signing status:** No errors have been found.

**List of activated apps:** Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_filter
  - user_external
  - user_ldap

**Nextcloud configuration:** {
    "system": {
        "instanceid": "oc1pdxd6jkd7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***.com",
        "loglevel": "0",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by nickvergessen** [comment]
Yeah there is no "mime sniffing" for various reasons.
