### ISSUE TITLE
upload rule doesnot prevent the large files from the client.

### ISSUE THREAD

**Issue by arm2arm** [nextcloud/files_accesscontrol#72]
1. windows nextcloud client 2.3.1
2. nextcloud server 12.0
3. enable app with options: 
file size **upload** **greater**  1KB
4. drag and drop 1GB file
5. copy 1GB file to the sync folder of the client.

### Expected behaviour
The files bigger 1KB should not upload over the web or client.
Before upload should throw "failed" message
### Actual behaviour
The web interface uploads the file right before finalizing throws  Failed 
The Windows client uploads arbitrary files to the cloud.

### Server configuration

**Operating system**:
debian 9 
**Web server:**
apache2
**Database:**
mariadb 
**PHP version:**
php 7.0, same with php 5.6

**Nextcloud version:** (see Nextcloud admin page)
12.0
**Where did you install Nextcloud from:**
from the main release page

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - bruteforcesettings
  - calendar
  - contacts
  - deck
  - files_external
  - files_snapshots
  - files_versions
  - firstrunwizard
  - impersonate
  - logreader
  - nextcloud_announcements
  - sharebymail
  - spreed
  - survey_client
  - tasks
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Comment by nickvergessen** [comment]
The reported version is EOL. If it still happens on a newer version feel free to create a new report.
