### ISSUE TITLE
Blank page on update from NC 12.0.4 to 13

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/files_accesscontrol#81]
nextcloud/server#7532

Nextcloud log:
{"reqId":"I76Rx37T3t6gby8zyNxc","level":3,"time":"2017-12-15T14:06:16+00:00","remoteAddr":"24.134.13.209","user":"--","app":"PHP","method":"GET","url":"\/","message":"Declaration of OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath) at \/var\/www\/nc_01\/nextcloud\/apps\/files_accesscontrol\/lib\/StorageWrapper.php#628","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.4.3"}

Apache log:
[Fri Dec 15 14:06:16.550444 2017] [proxy_fcgi:error] [pid 1185:tid 140167169410816] [client 24.134.13.209:55026] AH01071: Got error 'PHP message: PHP Fatal error:  Declaration of OCA\\FilesAccessControl\\StorageWrapper::copyFromStorage(OCP\\Files\\Storage $sourceStorage, $sourceInternalPath, $targetInternalPath) must be compatible with OCP\\Files\\Storage::copyFromStorage(OCP\\Files\\Storage\\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath) in /var/www/nc_01/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php on line 628\n'

This is fixed in 1.3.0 but there is no fixed version for NC 12.

**Comment by nickvergessen** [comment]
> must be compatible with OCP\Files\Storage::copyFromStorage(OCP\Files\Storage\IStorage $sourceStorage, $sourceInternalPath, $targetInternalPath)

This seems to indicate a mistake. In Nextcloud 12 the Signature of the method is actually: `OCP\Files\Storage::copyFromStorage(OCP\Files\Storage  $sourceStorage, $sourceInternalPath, $targetInternalPath)` as you can see here: https://github.com/nextcloud/server/blame/stable12/lib/public/Files/Storage.php#L404

The interface from your error message is only used in Nextcloud 13 and later.
Did you try an update and then reverted back to 12?

**Comment by nickvergessen** [comment]
As after reading the server issue I see you ran into this while doing the update.
So yeah, you need to disable the app and update it before you can use it with 13.

**Comment by endo64** [comment]
I had also same issue, upgrading from 12.04 to 13.01 completed but the page was down with HTTP 500.
I connected to the server via SSH and executed `sudo -u www-data php occ upgrade` inside the Nextcloud folder, solved the problem.

I saw below warnings in the output:

```
Disabled incompatible app: files_accesscontrol
Disabled incompatible app: files_automatedtagging
Disabled incompatible app: files_clipboard
Disabled incompatible app: files_retention
```

**Comment by ehirt** [comment]
I have no access to run occ but to the database and did the following steps:

1. disable above apps via database command: UPDATE oc_appconfig SET configvalue = "no" WHERE appid = "files_accesscontrol" AND configkey = "enabled" etc.
2. reload the website and now I could run the update as expected
3. re-enable the apps
