### ISSUE TITLE
Implement complex workflows and allow more triggers

### ISSUE THREAD

**Issue by moritz-weber** [nextcloud/files_accesscontrol#82]
I wrote up my thoughts on workflows on the forum: https://help.nextcloud.com/t/thoughts-on-workflows/24139

In know that this is not exactly the right place for such an issue, but I wanted my thoughts to be visible and persistent. There is no need to hurry, but I'd like to know where workflows are heading (feature-wise).

In the meantime I had a look at the existing workflow apps and understand, that the CacheWrapper allows more triggers than just file uploads. If it supported a reaction to changes of metadata (tags), complex workflows shouldn't be too hard to implement.

The existing apps are useful, but a possibility to combine them would simply be great.

**Comment by nickvergessen** [comment]
Yeah, lets discuss this further in the forum.
