### ISSUE TITLE
Nextcloud getting back to the root level after getting forbidden access to file or folder

### ISSUE THREAD

**Issue by C0pernic** [nextcloud/files_accesscontrol#84]
Hi there,

I'm using Nextcloud since a few days and, as it currently does not contain any way to edit permissions as an admin, I use file access control to do so. 

However, I've noticed when one clicks on a forbidden folder, it gets back to the root folder which is ergonomically annoying (in my opinion). Would it be a way to force Nextcloud to stay at the same nest level when the operation gets "forbidden" ?

Thanks in advance,

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
linux
**Web server:**

**Database:**
10.1.30-MariaDB
**PHP version:**
7.1.12
**Nextcloud version:** (see Nextcloud admin page)
12.0.4
**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**

**Operating system:**
macOS Sierra
#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by nickvergessen** [comment]
While that would be the desired behaviour, it is currently not possible.
The problem is that the files app directly reacts to the error code.

But maybe we can change this in the future.

**Comment by C0pernic** [comment]
okey ! Thank you for the answer ! See you in the future then !

**Comment by nickvergessen** [comment]
Since Nextcloud 19 blocked items are greyed out, so the redirect is not too unsuspected anymore.
