### ISSUE TITLE
Activity list destroyed/empty on android app after getting forbidden access to folder

### ISSUE THREAD

**Issue by Joe7new** [nextcloud/files_accesscontrol#85]
Similar problem as described in #84.
I set a system-tag to a folder as user (called 'private'). Then I logged in as admin and made the system-tag restricted (then a user can not delete or change it) . In next step I created a rule in file_accesscontrol app that accessing  folders with system tag 'private'  from android app is forbidden. 
After that  I tried to access this folder from my android phone and I got no access as expected .
****But after that activity list in android nextcloud-app was empty and didn't show anymore*.
And another problem then occured: When I tried to log in on server (doesn't matter what accont) again via webinterface (with desktop browser) the logging took very long time. Database affected  ? The only solution to get back activity list on android client was to log in as admin via webinterface, delete user and create the same user again (of course all files and tags were deleted too).
Althogh it still took a long time for logging in via webinterface.
As you see below nextcloud was running in Ubuntu/Xubuntu 16 LTS as vm.
The virtual machine isn't running now anymore, so I can't make more tests or send protocol. etc. 
(and at the moment I have very less time for new tests! ).
But I wanted to give you a hint to that strange behavior..
Regards Joe7

**Operating system**:
Xubuntu 12 LTS in virtual machine 

**Web server:** apache2.4

**Database:** mariadb 

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) latest

**Comment by nickvergessen** [comment]
This sounds like either the bruteforce protection kicked in, or the android app had another error

**Comment by nickvergessen** [comment]
@tobiasKaminsky any idea?

**Comment by tobiasKaminsky** [comment]
I suspect that that some parsing of the activity list errors.
As I never used tags and or file accesscontrol...

Even if one of the activity items fails, it should not prevent the whole remaining list from showing.
--> I'll try to harden it.

**Comment by Joe7new** [comment]
Thanks for your effort..... Joe7

**Comment by tobiasKaminsky** [comment]
There is a fix now in https://github.com/nextcloud/android-library/pull/106 and it will be in next stable 2.1 or next dev version.
