### ISSUE TITLE
unable to secure a public filedrop

### ISSUE THREAD

**Issue by bithugo** [nextcloud/files_accesscontrol#89]
The challenge is: creating a public filedrop and only allowing images up to max. 10 MB each.

### Steps to reproduce
1. define a folder UPLOAD and share it public (public filedrop) and tag it RESTRICTED
2. set up a ruleset using 
    filesystem-tag has tag RESTRICTED 
    file mime-type does not match /^image\/(gif|tiff|png|jpeg)$/i
3. set up a ruleset using
    filesystem-tag has tag RESTRICTED 
    file size (at upload) larger than 10 MB
4. access filedrop 

### Expected behaviour
You can upload images (gif, tiff, png and jpeg) up to 10 MB in size.
A PDF or DOCX will be rejected and any file larger than 10 MB will be rejected.

### Actual behaviour
Error message "file not found"
complete (sorry, it's in german):
Datei nicht gefunden
Das ausgewählte Dokument wurde auf dem Server nicht gefunden.

Sie können zur Rückkehr zu XYZ hier klicken.

If you set up a ruleset without mime-types, only restricting filesize to 10 MB, it will work as expected for that limitation.
So I think the shared folder cannot be accessed because of the mime-type restriction.

### Server configuration
**Operating system**:  linux, managed hosting, 1&1

**Web server:**

**Database:**
MySQL 5.5

**PHP version:**
PHP 7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.5.3

**Where did you install Nextcloud from:**
web-installer

**Signing status:**
No errors have been found.

**List of activated apps:**
file access control 1.2.5
and many more

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```
[nextcloud.log](https://github.com/nextcloud/files_accesscontrol/files/1686022/nextcloud.log)

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by bithugo** [comment]
Any ideas?
Has anyone already done some research on this issue?

**Comment by nickvergessen** [comment]
Sorry, it somehow slipped through my list.

Yes, the problem is that you deny accesss to anything but images, especially folders.
Try `/^httpd\/unix-directory|image\/(gif|tiff|png|jpeg)$/i` and it should work just fine.
