### ISSUE TITLE
Can`t create folders, upload files, download files

### ISSUE THREAD

**Issue by siny88** [nextcloud/files_accesscontrol#92]
Hi,
i have a problem, few days ago suddenly a problem occured.
I can`t download files which are shared public.
I can`t upload files and i can`t create folders.
When i create new user everything for that user works fine.
Any ideas?

**Comment by nickvergessen** [comment]
Please post the rules you are using

**Comment by siny88** [comment]
What do you mean saying rules?

**Comment by Schmuuu** [comment]
@siny88 when you configure this app "File Access Control" you define a rule set with rules. This is the basic configuration of this app and defines which download/ upload/ access is blocked (access control).
You find your rules in the admin settings section under "File access control".
