### ISSUE TITLE
Feature Request: Fine granular denying

### ISSUE THREAD

**Issue by richardhj** [nextcloud/files_accesscontrol#94]
### Expected behaviour
Per access control definition I want to choose whether to
- deny access (current exclusive behaviour),
- deny edit,
- deny delete (actually, this is what I need),
- deny share

in a checkbox wizard.
When you share a folder, the share dialog gives you already such options.

### Actual behaviour
A matching rule denies every access.

**Comment by GoetheG** [comment]
@raimund-schluessler I have the same issue and I am awaiting this settings to come soon. It would be also helpful if I had the chance to prevent ZIP download of folders within Nextcloud.

**Comment by nickvergessen** [comment]
We'll look into this but note that this is low priority unless there is a 
need for it from our enterprise customers. If you need it in your business, 
feel free to discuss it with your account manager. You can submit an inquiry 
over https://nextcloud.com/enterprise/buy/
