### ISSUE TITLE
not working with group folders

### ISSUE THREAD

**Issue by andreasmalta** [nextcloud/files_accesscontrol#96]
### Steps to reproduce
1. enable "Group folders" app, create a group folder
2. create a folder in the group folder and set a tag on the new folder
3. create a rule for the above tag and for user not member of a test group

### Expected behaviour
a user in the above group should not be able to open the folder

### Actual behaviour
the user can open the files/folders, they are not blocked

### Server configuration
**Operating system**: Centos7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1 (ius)

**Nextcloud version:** 13.0.1

**Where did you install Nextcloud from:** https://download.nextcloud.com

**Signing status:** No errors have been found.

**List of activated apps:**
Activity
Auditing / Logging
Brute-force settings
Collabora Online
Collaborative tags
Deleted files
Draw.io
External sites
File access control
File sharing
Group folders
Impersonate
Log Reader
Monitoring
Notifications
PDF viewer
Talk
Theming
Update notification
Versions
Video player
Zimbra Drive

**Nextcloud configuration:**
<?php
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxx',
  ),
  'datadirectory' => '/opt/nextclouddata/',
  'overwrite.cli.url' => 'https://xxxx',
  'dbtype' => 'mysql',
  'version' => '13.0.1.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'maintenance' => false,
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend',
      'arguments' => 
      array (
      ),
    ),
  ),
  'skeletondirectory' => '',
  'enable_previews' => false,
  'lost_password_link' => 'https://xxxx',
  'mail_from_address' => 'drive',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'xxxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpport' => '25',
  'mail_smtphost' => 'xxxx',
  'mail_smtpsecure' => 'tls',
);

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Zimbra Drive

### Client configuration
**Browser:** Chrome / Edge

**Operating system:** Windows 10 x64

**Comment by Schmuuu** [comment]
File Access Control is in general not working with Group folders right now. Another user tried to block uploading of ZIP files. While uploading zip files is successfully blocked everywhere else in Nextcloud (normal folders), the upload of zip files can be performed in Group folders and is not blocked there.

https://help.nextcloud.com/t/file-access-control-is-not-running/30801/7?u=schmu

So, would be really nice if File Access Control and Group Folders could work together.

**Comment by alexanderbuhler** [comment]
I had a quick look into the issue.

First thing fails is the check with `isBlockablePath`: It will check the path, with groupfolders usually beeing "__groupfolder/2" and return false since it doesn't have 3 slashes. From the user shared folder perspective this would validate root level, because user folders look like this: "/user.name/files/Rootfolder".

For dirty testing reasons, you could build around this with:

```
		if (substr_count($fullPath, '/') < 3 && strrpos($fullPath, "groupfolders") === false ) {
			return false;
		}
```

But then in the function `checkFileAccess` **rfa** will try to get matching operations and only throw the 'access denied' exception if $match isn't empty:

```

$match = $this->manager->getMatchingOperations('OCA\FilesAccessControl\Operation');

...

if (!empty($match)) {
  throw new ForbiddenException('Access denied', true);
```

Unfortunately, this function will return no matches for group folder paths. It may have to do with previous `translatePath` and `setFileInfo` functions not properly setting the `$this->manager` object.

Any ideas? I'm completely new to nextcloud and would surely need a couple of weeks to get into this. Besides this real showstopper everything seems to work well.

**Comment by SteffenDE** [comment]
Is anyone working on this?

**Comment by Adriien-M** [comment]
+1

**Comment by andreadelutti** [comment]
me too...thanks

**Comment by nickvergessen** [comment]
This is currently low priority unless there is a need for it from our enterprise customers. If you need it in your business, feel free to discuss it with your account manager. You can submit an inquiry over nextcloud.com/enterprise/buy/

**Comment by nickvergessen** [comment]
The reported version is EOL. If it still happens on a newer version feel free to create a new report.
