### ISSUE TITLE
Unclear translation

### ISSUE THREAD

**Issue by ygoe** [nextcloud/files_accesscontrol#98]
The German translation of "Request address" (supposedly) cannot be understood in German. The label "Entfernte Adresse anfordern" means something that doesn't apply to where it's placed. I guess I don't need to explain that to you. If someone who isn't speaking German is assigned to this issue, please ask for more details.

**Comment by nickvergessen** [comment]
I fixed the translation to `IP Adresse der Anfrage`
And it will be fixed in Nextcloud 13.0.3
