### ISSUE TITLE
Rules editor shows wrong operators

### ISSUE THREAD

**Issue by ygoe** [nextcloud/files_accesscontrol#99]
The rules editor breaks after trying out some fields. In an existing rule, switch through the fields (first select box) and look at the operators (second box). For a file tag, it should be "has tag" and "doesn't have tag". For others it's "less/greater than" etc. After trying out some more fields, the only operators I see are "between" and "not between" – for all fields! So I can now configure a rule where the file tag must be (not) between some text. Or the user membership must be (not) between some text. What does that even mean?

Update: This always happens after selecting the field "Anfrage-Zeitpunkt" (probably "request time", whatever that is). Even after clicking the "Reset" button, the operators are reset once but never updated to anything else again.

Chrome 66 on Windows 10.

**Comment by nickvergessen** [comment]
It works correctly, until you select "File system tag".

That is fixed with https://github.com/nextcloud/server/pull/9393 for 13.0.3
